version: '3'

services:
        web:
           build: .
#           command: python3 /code/manage.py makemigrations
#           command: python3 /code/manage.py migrate --noinput
#           command: python3 /code/manage.py runserver
           volumes:
                   - .:/code
           ports:
                   - "8000:8000"
#        networks:
#          app_net:
#            ipv4_address: "192.168.1.30/24"

